function createfigure(cdata1, X1, Y1, S1, C1)
%CREATEFIGURE(CDATA1,X1,Y1,S1,C1)
%  CDATA1:  image cdata
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 11-Jul-2013 13:41:39

% Create figure
figure1 = figure;
colormap('cool');

% Create axes
axes1 = axes('Parent',figure1,'Layer','top','FontSize',15,...
    'DataAspectRatio',[2 1 1],...
    'CLim',[0 1200]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-143.7 -142.3]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[60.1 60.55]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create image
image([-144 -141],[60 61],cdata1,'Parent',axes1);

% Create scatter
scatter(X1,Y1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none',...
    'Parent',axes1);

% Create title
title('Surface elevation during winter 2011/2012','FontSize',15);

% Create colorbar
colorbar('peer',axes1,'FontSize',20);

